# Generated by Django 3.0.4 on 2020-03-22 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('equipmentId', models.AutoField(db_column='EQUIPMENT_ID', primary_key=True, serialize=False, unique=True)),
                ('sportId', models.IntegerField(db_column='SPORT_ID')),
                ('equipmentAvailable', models.BooleanField(db_column='EQUIPMENT_AVAILABLE', default=False)),
                ('equipmentName', models.CharField(db_column='EQUIPMENT_NAME', max_length=50)),
            ],
            options={
                'db_table': 'EQUIPMENT',
            },
        ),
    ]
