# Generated by Django 3.0.4 on 2020-03-21 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sport',
            fields=[
                ('sportId', models.AutoField(db_column='SPORT_ID', primary_key=True, serialize=False, unique=True)),
                ('sportName', models.CharField(db_column='SPORT__NAME', max_length=100)),
                ('sportMaxPlayers', models.IntegerField(db_column='SPORT_MAX_PLAYER', default=0)),
                ('sportMinPlayers', models.IntegerField(db_column='SPORT_MIN_PLAYER', default=0)),
                ('sportTeamSport', models.BooleanField(db_column='SPORT_TEAM_SPORT', default=True)),
            ],
            options={
                'db_table': 'SPORT',
            },
        ),
    ]
