# Generated by Django 3.0.4 on 2020-03-21 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Area', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='area',
            name='areaName',
            field=models.CharField(db_column='AREA_NAME', default='COURT 1', max_length=20),
            preserve_default=False,
        ),
    ]
