# Generated by Django 3.0.4 on 2020-03-24 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('reservationId', models.AutoField(db_column='RESERVATION_ID', primary_key=True, serialize=False, unique=True)),
                ('usrId', models.IntegerField(db_column='USR_ID')),
                ('areaId', models.IntegerField(db_column='AREA_ID')),
                ('equipmentId', models.IntegerField(db_column='EQUIPMENT_ID')),
                ('sportId', models.IntegerField(db_column='SPORT_ID')),
                ('timeSlotId', models.IntegerField(db_column='TIME_SLOT_ID')),
                ('reservationDate', models.DateField(db_column='RESERVATION_DATE')),
            ],
            options={
                'db_table': 'RESERVATION',
            },
        ),
    ]
