# Generated by Django 3.0.4 on 2020-04-25 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reservation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='waitlist',
            field=models.IntegerField(db_column='WAITLIST', null=True),
        ),
    ]
