# Generated by Django 3.0.4 on 2020-03-17 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('usrId', models.AutoField(db_column='USR_ID', primary_key=True, serialize=False)),
                ('usrFirstName', models.CharField(db_column='USR_FIRST_NAME', max_length=100)),
                ('usrLastName', models.CharField(db_column='USR_LAST_NAME', max_length=100)),
                ('usrLoginName', models.CharField(db_column='USR_LOGIN_NAME', max_length=324)),
                ('usrPassword', models.CharField(db_column='USR_PASSWORD', max_length=100)),
                ('usrEmailId', models.CharField(db_column='USR_EMAIL_ID', max_length=324)),
                ('usrContact', models.CharField(db_column='USR_CONTACT', max_length=20)),
                ('usrRegistrationDate', models.DateTimeField(db_column='USR_REGISTRATION_DATE')),
            ],
            options={
                'db_table': 'USER',
            },
        ),
    ]
