# Generated by Django 3.0.4 on 2020-03-18 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='usrId',
            field=models.AutoField(db_column='USR_ID', primary_key=True, serialize=False, unique=True),
        ),
    ]
